# -*- coding: utf-8 -*-
"""cv lab 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0KAbOQTR5wxiEXEmFpMzkGOlsxie1Vj
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

#function  to display images
def show_comparison(original,sobel,prewit,canny):
    plt.figure(figsize=(12,10))

    #original image
    plt.subplot(2,2,1)
    plt.imshow(original,cmap='gray')
    plt.title("Original grayscale image")
    plt.axis('off')

    #sobel edge detection
    plt.subplot(2,2,2)
    plt.imshow(sobel,cmap='gray')
    plt.title("Sobel edge detection")
    plt.axis('off')


    #prewit edge detection
    plt.subplot(2,2,3)
    plt.imshow(prewit,cmap='gray')
    plt.title("Prewit edge detection")
    plt.axis('off')


    #canny edge deteetion
    plt.subplot(2,2,4)
    plt.imshow(canny,cmap='gray')
    plt.title("Canny edge detection")
    plt.axis('off')

    plt.tight_layout()
    plt.show()


#read an image
image = cv2.imread('image.jpg',0)

#read an image
image = cv2.imread('/content/lab 4',0)

if image is None:
  print("error:image not found")
else:
  print ("image loaded successfully")

  #sobel operator
  #gradient in x and y direction
  sobelx = cv2.Sobel(image,cv2.CV_64F,1,0,ksize=3)
  sobely = cv2.Sobel(image,cv2.CV_64F,0,1,ksize=3)

  #combine gradients
  sobel_combined=cv2.magnitude(sobelx,sobely)

  #prewit operator
  #define kernals (px,py)
  kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
  kernely = np.array([[-1,0,-1],[-1,0,-1],[-1,0,1]])
  #apply kernals using filter 2d
  prewitx = cv2.filter2D(image, cv2.CV_64F, kernelx)
  prewity = cv2.filter2D(image, cv2.CV_64F, kernely)
  prewit_combined=prewitx+prewity

  #canny edge detection
  #arguments:image,threshold1,threshold2
  canny_edges=cv2.Canny(image,100,200)

  #display results
  show_comparison(image,np.uint8(np.absolute(sobel_combined)),prewit_combined,canny_edges )